### PR TITLE
43:14 in the timeline

### PR DESCRIPTION
**Pull request by dglaude**
Put 43:14 @tannewt in the right place in the timeline...

### CODE REVIEW

**Comment by dhalbert** [comment]
Hi @dglaude, we don't reorder the entries based on time. We keep the list alphabetical (so people can add and find their entries to update while editing). The person running the meeting (usually @tannewt or @kattni) starts the Hug Reports or Status Reports, and it runs downward and then wraps around. Sometimes we need to skip someone too, and we just come back to them.

**Comment by dglaude** [comment]
Make some sense, and if it's been always like that...

My use case is to be able to read and listen simultaniously, this helps a lot with some accent, some audio glitch, some project or library name and because I am not a native listener.

So the chronological order, as a verbatim report, make sense to me.

**Comment by tannewt** [comment]
That's a good point. Since this is the first meeting of the year, let's change this one and do it going forwards. FYI @kattni

**Comment by dhalbert** [comment]
If you are going to do this, then the Hug Reports also need re-ordering.

**Comment by dglaude** [comment]
Let me handle the reordering, I will submit a PR.

**Pull request merged**
